# Generated by Django 2.0.2 on 2018-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbazar_app', '0011_product_flag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
