# Generated by Django 2.0.2 on 2018-11-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbazar_app', '0012_auto_20181125_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='college',
            new_name='hostel_name',
        ),
    ]
