# Generated by Django 2.0.2 on 2018-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbazar_app', '0013_auto_20181125_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('b', 'Books'), ('e', 'Electronics'), ('c', 'Cycles'), ('m', 'Manu Prac'), ('d', 'ED'), ('s', 'Sports'), ('o', 'Others')], default='others', max_length=120, null=True),
        ),
    ]
