# Generated by Django 2.0.2 on 2018-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbazar_app', '0014_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Electronics', 'Electronics'), ('Cycles', 'Cycles'), ('Manu Prac Apron', 'Manu Prac Apron'), ('ED', 'ED'), ('Sports', 'Sports'), ('Others', 'Others')], default='others', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_name',
            field=models.CharField(blank=True, choices=[('Visvesaraya Hostel', 'Visvesaraya Hostel'), ('S.N. Bose Hostel', 'S.N. Bose Hostel'), ('Ramanujan Hostel', 'Ramanujan Hostel'), ('Aryabhatta Hostel', 'Aryabhatta Hostel'), ('Rajputana Hostel', 'Rajputana Hostel')], default='u', help_text='college choice', max_length=1),
        ),
    ]
