# Generated by Django 2.0.2 on 2018-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbazar_app', '0015_auto_20181126_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
