# Generated by Django 2.0.2 on 2018-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbazar_app', '0016_auto_20181126_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel_name',
            field=models.CharField(blank=True, choices=[('Visvesaraya Hostel', 'Visvesaraya Hostel'), ('S.N. Bose Hostel', 'S.N. Bose Hostel'), ('Ramanujan Hostel', 'Ramanujan Hostel'), ('Aryabhatta Hostel', 'Aryabhatta Hostel'), ('Rajputana Hostel', 'Rajputana Hostel')], default='u', help_text='college choice', max_length=100),
        ),
    ]
